# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd79ee94f43424feeb825b44de4045d7744eaf4884964b2f530e55f20423057c7b566e4a7a401040352f5b0fcca0850dc12f6b4a1e2f0d31009edcb89df82e5

test:
  secret_key_base: 94a5ae7a3d5c09d6180b8e1bd6c113e3dea27399f3dd475df64ef88dc05ba89c73eda9d7cdd5ca9bc2e721d6b6f415fb7f8d41e6c1dbabfef1d6984de1e17855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
